#!/usr/bin/env sh
# One-time setup guide for a named Cloudflare Tunnel.
#
# This script prints instructions. It does NOT run cloudflared commands
# automatically because 'cloudflared login' requires an interactive browser
# OAuth flow that cannot be automated.
#
# Run through each step below manually.

echo ""
echo "======================================================"
echo "  GSD Dashboard — Named Cloudflare Tunnel Setup"
echo "======================================================"
echo ""
echo "This is a ONE-TIME setup. Once complete, your tunnel URL is permanent."
echo "You will never need to update GSD_DATA_URL on Railway again."
echo ""

echo "------------------------------------------------------"
echo "  Step 1: Log in to Cloudflare"
echo "------------------------------------------------------"
echo "Run:"
echo ""
echo "    cloudflared login"
echo ""
echo "This opens a browser window. Authorise the tunnel for your Cloudflare zone."
echo "cloudflared stores a certificate at ~/.cloudflared/cert.pem."
echo ""

echo "------------------------------------------------------"
echo "  Step 2: Create a named tunnel"
echo "------------------------------------------------------"
echo "Run (replace 'gsd-local' with any name you like):"
echo ""
echo "    cloudflared tunnel create gsd-local"
echo ""
echo "cloudflared creates a UUID-based credentials file at:"
echo "    ~/.cloudflared/<UUID>.json"
echo ""

echo "------------------------------------------------------"
echo "  Step 3: Route a DNS hostname to the tunnel"
echo "------------------------------------------------------"
echo "Run (replace YOUR_HOSTNAME with a subdomain on your Cloudflare zone):"
echo ""
echo "    cloudflared tunnel route dns gsd-local YOUR_HOSTNAME"
echo ""
echo "Example:  cloudflared tunnel route dns gsd-local gsd-local.yourdomain.com"
echo ""
echo "This creates a CNAME record in your Cloudflare DNS."
echo "Your permanent tunnel URL will be:  https://YOUR_HOSTNAME"
echo ""

echo "------------------------------------------------------"
echo "  Step 4: Add the tunnel name to .env"
echo "------------------------------------------------------"
echo "Run from the gsddashboard directory:"
echo ""
echo "    echo \"CLOUDFLARE_TUNNEL_NAME=gsd-local\" >> .env"
echo ""
echo "(Use the same name you chose in Step 2.)"
echo ""

echo "------------------------------------------------------"
echo "  Step 5: Set GSD_DATA_URL on Railway (one-time only)"
echo "------------------------------------------------------"
echo "In the Railway dashboard (or via CLI), set the environment variable:"
echo ""
echo "    GSD_DATA_URL=https://YOUR_HOSTNAME"
echo ""
echo "This only needs to be done ONCE. The URL never changes."
echo ""

echo "------------------------------------------------------"
echo "  Step 6: (Optional) Install the systemd service"
echo "------------------------------------------------------"
echo "To auto-start the tunnel on boot, run:"
echo ""
echo "    sudo cp /data/home/gsddashboard/scripts/tunnel.service /etc/systemd/system/gsd-tunnel.service"
echo "    sudo systemctl daemon-reload"
echo "    sudo systemctl enable gsd-tunnel"
echo "    sudo systemctl start gsd-tunnel"
echo ""
echo "Check status:"
echo ""
echo "    sudo systemctl status gsd-tunnel"
echo "    tail -f /tmp/gsd-tunnel.log"
echo ""

echo "======================================================"
echo "  Setup complete!"
echo "======================================================"
echo ""
echo "Once the tunnel is running, set GSD_DATA_URL on Railway to the permanent"
echo "hostname. This only needs to be done ONCE — the URL never changes."
echo ""
echo "Start the tunnel manually (or let systemd manage it):"
echo ""
echo "    sh /data/home/gsddashboard/scripts/tunnel.sh"
echo ""
