#!/usr/bin/env sh
# One-time setup guide for Cloudflare Tunnel (quick/trycloudflare mode).

echo ""
echo "======================================================"
echo "  GSD Dashboard — Cloudflare Tunnel Setup"
echo "======================================================"
echo ""
echo "Prerequisites:"
echo "  1. Install cloudflared (Debian/Ubuntu):"
echo "       curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb \\"
echo "         -o /tmp/cloudflared.deb && sudo dpkg -i /tmp/cloudflared.deb"
echo "     Verify: cloudflared --version"
echo ""
echo "  2. Authenticate the Railway CLI so tunnel.sh can sync the URL:"
echo "       railway login"
echo "       railway link                # select the gsd-dashboard project"
echo ""
echo "How it works:"
echo "  - scripts/tunnel.sh runs 'cloudflared tunnel --url http://localhost:4820'"
echo "    which prints a one-shot https://<random>.trycloudflare.com URL."
echo "  - The script parses that URL, writes it to .tunnel-url, and calls"
echo "    'railway variables --set GSD_DATA_URL=<url>' so the Railway-hosted"
echo "    frontend proxies /api/gsd/* and the terminal WebSocket through it."
echo "  - PM2 (gsd-tunnel) keeps cloudflared running; on restart a new URL is"
echo "    generated and Railway is re-synced automatically."
echo ""
echo "Start the tunnel:"
echo "    pm2 restart gsd-tunnel"
echo "    # or run directly: sh /data/home/gsddashboard/scripts/tunnel.sh"
echo ""
echo "Check status:"
echo "    cat /data/home/gsddashboard/.tunnel-url"
echo "    pm2 logs gsd-tunnel --lines 40"
echo "    curl -sS \"\$(cat /data/home/gsddashboard/.tunnel-url)/api/health\""
echo ""
