#!/usr/bin/env sh
# One-time setup guide for Tailscale Funnel.

echo ""
echo "======================================================"
echo "  GSD Dashboard — Tailscale Funnel Setup"
echo "======================================================"
echo ""
echo "Prerequisites:"
echo "  1. Install: curl -fsSL https://tailscale.com/install.sh | sh"
echo "  2. Auth:    sudo tailscale up      # follow browser link"
echo "  3. Enable Funnel for your tailnet:"
echo "       https://login.tailscale.com/admin/settings/features"
echo "     (or via ACL nodeAttrs \"funnel\" grant)"
echo ""
echo "Find your Funnel URL:"
echo "    sudo tailscale status --json | grep DNSName"
echo "  Then strip the trailing dot: https://<host>.<tailnet>.ts.net"
echo ""
echo "Configure:"
echo "    .env               TAILSCALE_FUNNEL_URL=https://<host>.<tailnet>.ts.net"
echo "    Railway variable   GSD_DATA_URL=https://<host>.<tailnet>.ts.net"
echo ""
echo "Start the tunnel (PM2 supervised):"
echo "    pm2 restart gsd-tunnel"
echo "    # or run directly: sh /data/home/gsddashboard/scripts/tunnel.sh"
echo ""
echo "Check status:"
echo "    sudo tailscale funnel status"
echo "    pm2 logs gsd-tunnel --lines 20"
echo ""
echo "Note: tunnel.sh will start tailscaled (userspace mode) itself if it"
echo "isn't already running. Requires passwordless sudo."
echo ""
